image: maven:3.8.4-openjdk-21
stages:
  - build
  - test
  - package
  - deploy

variables:
  MAVEN_OPTS: -Dmaven.repo.local=.m2/repository"
cache:
  paths:
    - .m2/repository/

build-job:
  stage: build
  script:
    - echo "Building the project..."
    - mvn clean compile
  artifacts:
    paths:
      - target/

test-job:
  stage: test
  script:
    - echo " Packaging thr application ... "
    - mvn package -DskipTests
  artifacts:
    paths:
      - target/*.jar

deploy-job:
  stage: deploy
  only:
    - main
  script:
    - echo "Deploying application..."
    - scp target/*.jar user@yourserver:/path/to/deploy/

