version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: shima_SQL
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: aa!123456
      MYSQL_DATABASE: DMS_database
      MYSQL_USER: shima
      MYSQL_PASSWORD: Aa!123456
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  app:
    build: .
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/DMS_database
      SPRING_DATASOURCE_USERNAME: shima
      SPRING_DATASOURCE_PASSWORD: Aa!123456
    ports:
      - "8080:8080"
    volumes:
      - ./app:/app

volumes:
  mysql-data: {}